// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckFFmpeg():Promise<main.ProcessResult>;

export function GetAudioInfo(arg1:string):Promise<main.ProcessResult>;

export function ProcessAudio(arg1:string,arg2:string,arg3:number,arg4:boolean):Promise<main.ProcessResult>;

export function SelectAudioFile():Promise<main.FileInfo>;

export function SelectOutputPath(arg1:string):Promise<string>;

export function ShowErrorDialog(arg1:string,arg2:string):Promise<void>;

export function ShowInfoDialog(arg1:string,arg2:string):Promise<void>;
