// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFFmpeg() {
  return window['go']['main']['App']['CheckFFmpeg']();
}

export function GetAudioInfo(arg1) {
  return window['go']['main']['App']['GetAudioInfo'](arg1);
}

export function ProcessAudio(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ProcessAudio'](arg1, arg2, arg3, arg4);
}

export function SelectAudioFile() {
  return window['go']['main']['App']['SelectAudioFile']();
}

export function SelectOutputPath(arg1) {
  return window['go']['main']['App']['SelectOutputPath'](arg1);
}

export function ShowErrorDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowErrorDialog'](arg1, arg2);
}

export function ShowInfoDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowInfoDialog'](arg1, arg2);
}
